page_table = false
# 256 MB
total_mem_size = 0x10000000
# 1 MB
stack_mem_size = 0x100000

# Symbols defined in user code that should take precedence over built-in shims.
[user_preferred_symbol]
strlen = true
