# Some instances of Cargo & miri subprocess
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri miri run --features --target-dir /KMiri/tests/os/target -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem --profile=dev
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri miri run --features --target-dir /KMiri/tests/os/target -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem --profile=dev
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo run --target x86_64-unknown-linux-gnu --config target.'cfg(all())'.runner=["/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri", 'runner'] --target-dir /KMiri/tests/os/target/miri --features -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem --profile=dev
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg -Wwarnings
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri --print=target-spec-json -Zunstable-options
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri - --crate-name ___ --print=file-names --cfg ktest -C link-arg=-Tmiri.ld -C relocation-model=static -C relro-level=off -C force-unwind-tables=yes --check-cfg cfg(ktest) -C no-redzone=y -C target-feature=+ermsb --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg -Wwarnings
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri --sysroot /root/.cache/miri - --crate-name ___ --print=file-names --cfg ktest -C link-arg=-Tmiri.ld -C relocation-model=static -C relro-level=off -C force-unwind-tables=yes --check-cfg cfg(ktest) -C no-redzone=y -C target-feature=+ermsb --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg -Wwarnings
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri --sysroot /root/.cache/miri --print=target-spec-json -Zunstable-options --cfg ktest -C link-arg=-Tmiri.ld -C relocation-model=static -C relro-level=off -C force-unwind-tables=yes --check-cfg cfg(ktest) -C no-redzone=y -C target-feature=+ermsb --target x86_64-unknown-linux-gnu
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri -vV
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri -vV
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri --crate-name core --edition=2024 /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=160 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --warn=unexpected_cfgs --check-cfg cfg(no_fp_fmt_parse) --check-cfg cfg(feature, values(any())) --check-cfg cfg(target_has_reliable_f16) --check-cfg cfg(target_has_reliable_f16_math) --check-cfg cfg(target_has_reliable_f128) --check-cfg cfg(target_has_reliable_f128_math) --check-cfg cfg(llvm_enzyme) --check-cfg cfg(docsrs,test) --check-cfg cfg(feature, values("debug_refcell", "llvm_enzyme", "optimize_for_size", "panic_immediate_abort")) -C metadata=ef6fe3f059612669 -C extra-filename=-c06e9e878cc0a338 --out-dir /KMiri/tests/os/target/miri/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/KMiri/tests/os/target/miri/x86_64-unknown-linux-gnu/debug/deps -L dependency=/KMiri/tests/os/target/miri/debug/deps --cap-lints allow --cfg ktest -C link-arg=-Tmiri.ld -C relocation-model=static -C relro-level=off -C force-unwind-tables=yes --check-cfg cfg(ktest) -C no-redzone=y -C target-feature=+ermsb
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri --crate-name build_script_build --edition=2024 /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/compiler-builtins/compiler-builtins/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=160 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg feature="compiler-builtins" --cfg feature="default" --cfg feature="mem" --cfg feature="rustc-dep-of-std" --check-cfg cfg(docsrs,test) --check-cfg cfg(feature, values("c", "compiler-builtins", "default", "mangled-names", "mem", "no-asm", "no-f16-f128", "rustc-dep-of-std", "unstable-public-internals")) -C metadata=d83307d617167ae3 -C extra-filename=-f6fb91fede64f633 --out-dir /KMiri/tests/os/target/miri/debug/build/compiler_builtins-f6fb91fede64f633 -Z force-unstable-if-unmarked -L dependency=/KMiri/tests/os/target/miri/debug/deps --cap-lints allow
/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri --sysroot /root/.cache/miri --crate-name core --edition=2024 /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=160 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --warn=unexpected_cfgs --check-cfg cfg(no_fp_fmt_parse) --check-cfg cfg(feature, values(any())) --check-cfg cfg(target_has_reliable_f16) --check-cfg cfg(target_has_reliable_f16_math) --check-cfg cfg(target_has_reliable_f128) --check-cfg cfg(target_has_reliable_f128_math) --check-cfg cfg(llvm_enzyme) --check-cfg cfg(docsrs,test) --check-cfg cfg(feature, values("debug_refcell", "llvm_enzyme", "optimize_for_size", "panic_immediate_abort")) -C metadata=ef6fe3f059612669 -C extra-filename=-c06e9e878cc0a338 --out-dir /KMiri/tests/os/target/miri/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/KMiri/tests/os/target/miri/x86_64-unknown-linux-gnu/debug/deps -L dependency=/KMiri/tests/os/target/miri/debug/deps --cap-lints allow --cfg ktest -C link-arg=-Tmiri.ld -C relocation-model=static -C relro-level=off -C force-unwind-tables=yes --check-cfg cfg(ktest) -C no-redzone=y -C target-feature=+ermsb


   Compiling libc v0.2.184
process 18631 is executing new program: /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri
[Switching to process 18631]
                                                                                                                                                                Thread 24.1 "cargo-miri" hit Catchpoint 1 (exec'd /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri), 0x000073b012936540 in ??    () from /lib64/ld-linux-x86-64.so.2
[inferior=24 pid=18631] [stop_handler] /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri
>>> i proc cmdline
process 18631
cmdline = '/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/cargo-miri /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri --crate-name build_script_build --edition=2021 /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/quote-1.0.45/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=160 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg feature="default" --cfg feature="proc-macro" --check-cfg cfg(docsrs,test) --check-cfg cfg(feature, values("default", "proc-macro")) -C metadata=e65c8405da662b61 -C extra-filename=-6bf14492c6bdd53d --out-dir /KMiri/tests/os/target/miri/debug/build/quote-6bf14492c6bdd53d -L dependency=/KMiri/tests/os/target/miri/debug/deps --cap-lints allow'

/root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/bin/miri --sysroot /root/.cache/miri --crate-name core --edition=2024 /root/.rustup/toolchains/nightly-2025-12-06-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=160 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --warn=unexpected_cfgs --check-cfg cfg(no_fp_fmt_parse) --check-cfg cfg(feature, values(any())) --check-cfg cfg(target_has_reliable_f16) --check-cfg cfg(target_has_reliable_f16_math) --check-cfg cfg(target_has_reliable_f128) --check-cfg cfg(target_has_reliable_f128_math) --check-cfg cfg(llvm_enzyme) --check-cfg cfg(docsrs,test) --check-cfg cfg(feature, values("debug_refcell", "llvm_enzyme", "optimize_for_size", "panic_immediate_abort")) -C metadata=ef6fe3f059612669 -C extra-filename=-c06e9e878cc0a338 --out-dir /KMiri/tests/os/target/miri/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/KMiri/tests/os/target/miri/x86_64-unknown-linux-gnu/debug/deps -L dependency=/KMiri/tests/os/target/miri/debug/deps --cap-lints allow --cfg ktest -C link-arg=-Tmiri.ld -C relocation-model=static -C relro-level=off -C force-unwind-tables=yes --check-cfg cfg(ktest) -C no-redzone=y -C target-feature=+ermsb
