name: KMiri

on:
  push:

jobs:
  KMiri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install toolchain
        run: rustc -V

      - name: Check default miri
        run: |
          rustup component add miri
          ls -alh $(rustc --print=sysroot)/bin/*miri
          cargo miri --version

      - name: Install kmiri & osdk
        run: |
          ./tool/install_miri_osdk.sh
          cargo miri --version
          cargo osdk --version

      - name: Run kmiri on tests/os
        working-directory: tests/os
        run: OSDK_LOCAL_DEV=1 cargo osdk miri test

  Asterinas:
    runs-on: ubuntu-latest
    container:
      # Environment required by Asterinas.
      image: asterinas/asterinas:0.17.0-20260114
      options: --device=/dev/kvm --privileged
      volumes:
        # Map the following directories on the host into the container so that
        # the container can remove them to save some precious disk space (~16GB),
        # which is quite limited on free-tier Github runners.
        - /usr/lib/google-cloud-sdk:/usr/lib/google-cloud-sdk
        - /usr/local/lib/android:/usr/local/lib/android
        - /usr/share/dotnet:/usr/share/dotnet
    steps:
      - uses: actions/checkout@v6

      - name: Fix git ownership
        run: |
          git config --global --add safe.directory /__w/KMiri/KMiri
          git config --global --add safe.directory '*'

      - name: Check out asterinas
        run: git submodule update --init asterinas

      - name: make check
        working-directory: asterinas
        env:
          RUSTFLAGS: --cfg=miri
        run: echo $VDSO_LIBRARY_DIR && make test

      - name: make check-ostd
        working-directory: asterinas
        run: make check-ostd
